version: '3.7'

services:
  bot:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: shoplist_bot
    networks:
      - shoplist
    ports:
      - 443:443
    tty: true
    restart: unless-stopped
    volumes:
      - ./db/buget.db:/go/src/github.com/Frosin/shoplist-telegram-bot/db/buget.db
      - ./db/shoplist.db:/go/src/github.com/Frosin/shoplist-telegram-bot/db/shoplist.db

networks:
  shoplist:
    external: true
